### ISSUE TITLE
Model stopped oscillating

### ISSUE THREAD

**Issue by StevenBackues** [luciansmith/network-modeling-2021-example#2]
The commit  071ea752c85678c4dc394dbf683cd78eda693839 stopped the model from oscillating.  In this commit, "More literature fixes", the value for k0 was changed from 50 to 4.82, which is a surprisingly large change.  I suspect that 48.2 might have been intended.  Changing the value of k0 to 4.8 restores the oscilation, as shown below.

![image](https://user-images.githubusercontent.com/39271032/126524145-ba055c9d-96af-4355-a0b1-2563a876acb6.png)

Now I will try to do a commit to fix this.

**Comment by luciansmith** [comment]
Correct!  You even guessed the correct fix.
