### ISSUE TITLE
Variable initialization

### ISSUE THREAD

**Issue by oshehoma** [luciansmith/network-modeling-2021-example#3]
In the [More literature fixes commit](https://github.com/luciansmith/network-modeling-2021-example/commit/071ea752c85678c4dc394dbf683cd78eda693839#diff-13bb24abca141c3320f15088043ccf5f4dd344fab4e76c3baab49c93066ce142), changing k0 from 50 to 4.82 results in loss of oscillation.  Returning k0 to 50 recovers oscillations (while keeping the k4 fix)

Side question: Is there a better way to link to the place/commit/file where the issue is?

**Comment by luciansmith** [comment]
Github has a thing where if you just paste in the long unique commit ID, it'll link directly to it with its shorthand, so you can put in the whole URL:

```
https://github.com/luciansmith/network-modeling-2021-example/commit/071ea752c85678c4dc394dbf683cd78eda693839
```

https://github.com/luciansmith/network-modeling-2021-example/commit/071ea752c85678c4dc394dbf683cd78eda693839

or even just the string:

```
071ea752c85678c4dc394dbf683cd78eda693839 
```

071ea752c85678c4dc394dbf683cd78eda693839

**Comment by oshehoma** [comment]
Great, thank you!

Really enjoying the workshop. I'm sure it's very different as a virtual
setting but it's wonderful for someone like me who wouldn't be able to
attend an in-person meeting at this time!

**Comment by luciansmith** [comment]
Glad you're enjoying the workshop!  Definitely let us know if there's anything in particular that you felt helped a lot or didn't quite work for whatever reason.  And I'm glad you got the right answer ;-)
